import { Rule, Violation } from './types';

export const mockRules: Rule[] = [
  {
    id: '1',
    number: 1,
    title: 'We Listen Fully',
    description: 'When one speaks, the other gives undivided attention. No phones, no distractions.',
    category: 'communication',
    consequence: 'You owe a 30-minute undivided conversation',
    createdBy: 'mock-user-a',
    createdAt: new Date('2024-01-15'),
    status: 'active',
    approvalStatus: 'approved',
    approvalConfirmedBy: ['mock-user-a', 'mock-user-b'],
    lockedForDeletion: true,
    deletionConfirmedBy: [],
  },
  {
    id: '2',
    number: 2,
    title: 'Honesty Above All',
    description: 'We speak our truth with kindness, even when it is difficult.',
    category: 'trust',
    consequence: 'Write a letter explaining your feelings',
    createdBy: 'mock-user-b',
    createdAt: new Date('2024-01-15'),
    status: 'active',
    approvalStatus: 'approved',
    approvalConfirmedBy: ['mock-user-a', 'mock-user-b'],
    lockedForDeletion: true,
    deletionConfirmedBy: [],
  },
  {
    id: '3',
    number: 3,
    title: 'Never Sleep Angry',
    description: 'We resolve conflicts before the day ends, or at least agree to revisit them peacefully.',
    category: 'communication',
    consequence: 'Stay up and talk until resolved',
    createdBy: 'mock-user-a',
    createdAt: new Date('2024-01-20'),
    status: 'active',
    approvalStatus: 'approved',
    approvalConfirmedBy: ['mock-user-a', 'mock-user-b'],
    lockedForDeletion: true,
    deletionConfirmedBy: [],
  },
  {
    id: '4',
    number: 4,
    title: 'Respect Personal Space',
    description: 'Everyone needs moments of solitude. We honor that need without question.',
    category: 'boundaries',
    consequence: 'Plan a solo self-care day for your partner',
    createdBy: 'mock-user-b',
    createdAt: new Date('2024-02-01'),
    status: 'active',
    approvalStatus: 'approved',
    approvalConfirmedBy: ['mock-user-a', 'mock-user-b'],
    lockedForDeletion: true,
    deletionConfirmedBy: [],
  },
  {
    id: '5',
    number: 5,
    title: 'Daily Gratitude',
    description: 'Share one thing you appreciate about each other every day.',
    category: 'affection',
    consequence: 'Write 10 things you love about your partner',
    createdBy: 'mock-user-a',
    createdAt: new Date('2024-02-10'),
    status: 'broken',
    approvalStatus: 'approved',
    approvalConfirmedBy: ['mock-user-a', 'mock-user-b'],
    lockedForDeletion: true,
    deletionConfirmedBy: [],
  },
  {
    id: '6',
    number: 6,
    title: 'No Raising Voices',
    description: 'Disagreements are discussed calmly. Volume does not equal validity.',
    category: 'respect',
    consequence: 'You owe a hug and a sincere apology',
    createdBy: 'mock-user-b',
    createdAt: new Date('2024-02-15'),
    status: 'active',
    approvalStatus: 'approved',
    approvalConfirmedBy: ['mock-user-a', 'mock-user-b'],
    lockedForDeletion: true,
    deletionConfirmedBy: [],
  },
];

export const mockViolations: Violation[] = [
  {
    id: 'v1',
    ruleId: '5',
    brokenBy: 'A',
    note: 'Forgot to share gratitude for two days in a row',
    forgiven: false,
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'v2',
    ruleId: '1',
    brokenBy: 'B',
    note: 'Was on phone during important conversation',
    forgiven: true,
    createdAt: new Date('2024-02-28'),
  },
  {
    id: 'v3',
    ruleId: '6',
    brokenBy: 'A',
    note: 'Raised voice during argument about dishes',
    forgiven: true,
    createdAt: new Date('2024-02-20'),
  },
];
